sudo: false
language: ruby
rvm:
  - 2.6.3

before_install:
  - sudo apt-get update
  - gem install bundler -v 2.1.4

before_script:
  - psql -c 'create database ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp .env.travis .env
  - bin/rails db:migrate RAILS_ENV=test

services:
  - postgresql
  - redis

script: bundle exec rspec